FROM ubuntu:latest

ARG IGGY_SERVER_PATH
RUN test -n "$IGGY_SERVER_PATH" || (echo "IGGY_SERVER_PATH not set" && false)

WORKDIR /iggy

COPY configs ./configs
COPY ${IGGY_SERVER_PATH} ./

RUN chmod +x ./iggy-server

CMD ["/iggy/iggy-server"]
