pub mod args;
pub mod binary;
pub mod bytes_serializable;
pub mod client;
pub mod client_error;
pub mod client_provider;
pub mod clients;
pub mod command;
pub mod consumer;
pub mod consumer_groups;
pub mod consumer_offsets;
pub mod error;
pub mod errors;
pub mod http;
pub mod identifier;
pub mod message_handler;
pub mod messages;
pub mod models;
pub mod partitioner;
pub mod partitions;
pub mod quic;
pub mod sizeable;
pub mod streams;
pub mod system;
pub mod tcp;
pub mod topics;
pub mod users;
pub mod utils;
pub mod validatable;

pub const DEFAULT_ROOT_USER_ID: u32 = 1;
pub const DEFAULT_ROOT_USERNAME: &str = "iggy";
pub const DEFAULT_ROOT_PASSWORD: &str = "iggy";
