@url = http://localhost:3000
@stream_id = 1
@topic_id = 1
@partition_id = 1
@group_id = 1
@consumer_id = 1
@message_1_payload_base64 = aGVsbG8=
@message_2_payload_base64 = d29ybGQ=

###
GET {{url}}

###
GET {{url}}/clients

###
GET {{url}}/ping

###
POST {{url}}/kill

###
GET {{url}}/streams

###
GET {{url}}/streams/{{stream_id}}

###
POST {{url}}/streams
Content-Type: application/json

{
  "stream_id": {{stream_id}},
  "name": "stream 1"
}

###
DELETE {{url}}/streams/{{stream_id}}

###
GET {{url}}/streams/{{stream_id}}/topics

###
GET {{url}}/streams/{{stream_id}}/topics/{{topic_id}}

###
POST {{url}}/streams/{{stream_id}}/topics
Content-Type: application/json

{
  "topic_id": {{topic_id}},
  "name": "topic 1",
  "partitions_count": 3
}

###
DELETE {{url}}/streams/{{stream_id}}/topics/{{topic_id}}

###
POST {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/messages
Content-Type: application/json

{
  "key_kind": "partition_id",
  "key_value": 1,
  "messages": [{
    "id": 0,
    "payload": "{{message_1_payload_base64}}"
  }, {
    "id": 0,
    "payload": "{{message_2_payload_base64}}"
  }]
}

###
GET {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/messages?consumer_id={{consumer_id}}&partition_id={{partition_id}}&kind=offset&value=0&count=10&auto_commit=false

###
PUT {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/messages/offsets
Content-Type: application/json

{
  "consumer_id": {{consumer_id}},
  "partition_id": {{partition_id}},
  "offset": 1
}

###
GET {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/messages/offsets?consumer_id={{consumer_id}}&partition_id={{partition_id}}

###
GET {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/groups

###
GET {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/groups/{{group_id}}

###
POST {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/groups
Content-Type: application/json

{
  "group_id": {{group_id}}
}

###
DELETE {{url}}/streams/{{stream_id}}/topics/{{topic_id}}/groups/{{group_id}}