INSERT INTO error_codes (name, code, template, signature, converts_from, documentation)
VALUES  ('error', 1, 'Error', null, null, ''),
        ('invalid_configuration', 2, 'Invalid configuration', null, null, ''),
        ('invalid_command', 3, 'Invalid command', null, null, ''),
        ('invalid_format', 4, 'Invalid format', null, null, ''),
        ('feature_unavailable', 5, 'Feature is unavailable', null, null, ''),
        ('cannot_create_base_directory', 10, 'Cannot create base directory', null, null, ''),
        ('resource_not_found', 20, 'Resource with key: {0} was not found.', 'String', null, ''),
        ('cannot_load_resource', 21, 'Cannot load resource with key: {0}', 'String', null, ''),
        ('cannot_save_resource', 22, 'Cannot save resource with key: {0}', 'String', null, ''),
        ('cannot_delete_resource', 23, 'Cannot delete resource with key: {0}', 'String', null, ''),
        ('cannot_serialize_resource', 24, 'Cannot serialize resource with key: {0}', 'String', null, ''),
        ('cannot_deserialize_resource', 25, 'Cannot deserialize resource with key: {0}', 'String', null, ''),
        ('unauthenticated', 40, 'Unauthenticated', null, null, ''),
        ('unauthorized', 41, 'Unauthorized', null, null, ''),
        ('invalid_credentials', 42, 'Invalid credentials', null, null, ''),
        ('invalid_username', 43, 'Invalid username', null, null, ''),
        ('invalid_password', 44, 'Invalid password', null, null, ''),
        ('invalid_user_status', 45, 'Invalid user status', null, null, ''),
        ('user_already_exists', 46, 'User already exists', null, null, ''),
        ('user_inactive', 47, 'User inactive', null, null, ''),
        ('cannot_delete_user', 48, 'Cannot delete user with ID: {0}', 'u32', null, ''),
        ('cannot_change_permissions', 49, 'Cannot change permissions for user with ID: {0}', 'u32', null, ''),
        ('not_connected', 51, 'Not connected', null, null, ''),
        ('request_error', 52, 'Request error', null, 'reqwest::Error', ''),
        ('invalid_encryption_key', 60, 'Invalid encryption key', null, null, ''),
        ('cannot_encrypt_data', 61, 'Cannot encrypt data', null, null, ''),
        ('cannot_decrypt_data', 62, 'Cannot decrypt data', null, null, ''),
        ('client_not_found', 100, 'Client with ID: {0} was not found.', 'u32', null, ''),
        ('invalid_client_id', 101, 'Invalid client ID', null, null, ''),
        ('io_error', 200, 'IO error', null, 'io::Error', ''),
        ('write_error', 201, 'Write error', null, 'WriteError', ''),
        ('cannot_parse_utf8', 202, 'Cannot parse UTF8', null, 'Utf8Error', ''),
        ('cannot_parse_int', 203, 'Cannot parse integer', null, 'ParseIntError', ''),
        ('cannot_parse_slice', 204, 'Cannot parse integer', null, 'TryFromSliceError', ''),
        ('http_response_error', 300, 'HTTP response error, status: {0}, body: {1}', 'u16, String', null, ''),
        ('request_middleware_error', 301, 'Request middleware error', null, 'reqwest_middleware::Error', ''),
        ('cannot_create_endpoint', 302, 'Cannot create endpoint', null, null, ''),
        ('cannot_parse_url', 303, 'Cannot parse URL', null, null, ''),
        ('invalid_response', 304, 'Invalid response: {0}', 'u32', null, ''),
        ('empty_response', 305, 'Empty response', null, null, ''),
        ('cannot_parse_address', 306, 'Cannot parse address', null, 'AddrParseError', ''),
        ('read_error', 307, 'Read error', null, 'ReadError', ''),
        ('connection_error', 308, 'Connection error', null, 'ConnectionError', ''),
        ('read_to_end_error', 309, 'Read to end error', null, 'ReadToEndError', ''),
        ('cannot_create_streams_directory', 1000, 'Cannot create streams directory', null, null, ''),
        ('cannot_create_stream_directory', 1001, 'Cannot create stream with ID: {0} directory', 'u32', null, ''),
        ('cannot_create_stream_info', 1002, 'Failed to create stream info file for stream with ID: {0}', 'u32', null, ''),
        ('cannot_update_stream_info', 1003, 'Failed to update stream info for stream with ID: {0}', 'u32', null, ''),
        ('cannot_open_stream_info', 1004, 'Failed to open stream info file for stream with ID: {0}', 'u32', null, ''),
        ('cannot_read_stream_info', 1005, 'Failed to read stream info file for stream with ID: {0}', 'u32', null, ''),
        ('cannot_create_stream', 1006, 'Failed to create stream with ID: {0}', 'u32', null, ''),
        ('cannot_delete_stream', 1007, 'Failed to delete stream with ID: {0}', 'u32', null, ''),
        ('cannot_delete_stream_directory', 1008, 'Failed to delete stream directory with ID: {0}', 'u32', null, ''),
        ('stream_id_not_found', 1009, 'Stream with ID: {0} was not found.', 'u32', null, ''),
        ('stream_name_not_found', 1010, 'Stream with name: {0} was not found.', 'String', null, ''),
        ('stream_id_already_exists', 1011, 'Stream with ID: {0} already exists.', 'u32', null, ''),
        ('stream_name_already_exists', 1012, 'Stream with name: {0} already exists.', 'String', null, ''),
        ('invalid_stream_name', 1013, 'Invalid stream name', null, null, ''),
        ('invalid_stream_id', 1014, 'Invalid stream ID', null, null, ''),
        ('cannot_read_streams', 1015, 'Cannot read streams', null, null, ''),
        ('cannot_create_topics_directory', 2000, 'Cannot create topics directory for stream with ID: {0}', 'u32', null, ''),
        ('cannot_create_topic_directory', 2001, 'Failed to create directory for topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_create_topic_info', 2002, 'Failed to create topic info file for topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_update_topic_info', 2003, 'Failed to update topic info for topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_open_topic_info', 2004, 'Failed to open topic info file for topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_read_topic_info', 2005, 'Failed to read topic info file for topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_create_topic', 2006, 'Failed to create topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_delete_topic', 2007, 'Failed to delete topic with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_delete_topic_directory', 2008, 'Failed to delete topic directory with ID: {0} for stream with ID: {1}.', 'u32, u32', null, ''),
        ('cannot_poll_topic', 2009, 'Cannot poll topic', null, null, ''),
        ('topic_id_not_found', 2010, 'Topic with ID: {0} for stream with ID: {1} was not found.', 'u32, u32', null, ''),
        ('topic_name_not_found', 2011, 'Topic with name: {0} for stream with ID: {1} was not found.', 'String, u32', null, ''),
        ('topic_id_already_exists', 2012, 'Topic with ID: {0} for stream with ID: {1} already exists.', 'u32, u32', null, ''),
        ('topic_name_already_exists', 2013, 'Topic with name: {0} for stream with ID: {1} already exists.', 'String, u32', null, ''),
        ('invalid_topic_name', 2014, 'Invalid topic name', null, null, ''),
        ('too_many_partitions', 2015, 'Too many partitions', null, null, ''),
        ('invalid_topic_id', 2016, 'Invalid topic ID', null, null, ''),
        ('cannot_read_topics', 2017, 'Cannot read topics for stream with ID: {0}', 'u32', null, ''),
        ('cannot_create_partition', 3000, 'Cannot create partition with ID: {0} for stream with ID: {1} and topic with ID: {2}', 'u32, u32, u32', null, ''),
        ('cannot_create_partitions_directory', 3001, 'Failed to create directory for partitions for stream with ID: {0} and topic with ID: {1}', 'u32, u32', null, ''),
        ('cannot_create_partition_directory', 3002, 'Failed to create directory for partition with ID: {0} for stream with ID: {1} and topic with ID: {2}', 'u32, u32, u32', null, ''),
        ('cannot_open_partition_log_file', 3003, 'Cannot open partition log file', null, null, ''),
        ('cannot_read_partitions', 3004, 'Failed to read partitions directories for topic with ID: {0} and stream with ID: {1}', 'u32, u32', null, ''),
        ('cannot_delete_partition', 3005, 'Failed to delete partition with ID: {0} for stream with ID: {1} and topic with ID: {2}', 'u32, u32, u32', null, ''),
        ('cannot_delete_partition_directory', 3006, 'Failed to delete partition directory with ID: {0} for stream with ID: {1} and topic with ID: {2}', 'u32, u32, u32', null, ''),
        ('partition_not_found', 3007, 'Partition with ID: {0} for topic with ID: {1} for stream with ID: {2} was not found.', 'u32, u32, u32', null, ''),
        ('no_partitions', 3008, 'Topic with ID: {0} for stream with ID: {1} has no partitions.', 'u32, u32', null, ''),
        ('segment_not_found', 4000, 'Segment not found', null, null, ''),
        ('segment_closed', 4001, 'Segment with start offset: {0} and partition with ID: {1} is closed', 'u64, u32', null, ''),
        ('invalid_segment_size', 4002, 'Segment size is invalid', 'u64', null, ''),
        ('cannot_create_segment_log_file', 4003, 'Failed to create segment log file for path: {0}.', 'String', null, ''),
        ('cannot_create_segment_index_file', 4004, 'Failed to create segment index file for path: {0}.', 'String', null, ''),
        ('cannot_create_segment_time_index_file', 4005, 'Failed to create segment time index file for path: {0}.', 'String', null, ''),
        ('cannot_save_messages_to_segment', 4006, 'Cannot save messages to segment', null, null, ''),
        ('cannot_save_index_to_segment', 4007, 'Cannot save index to segment', null, null, ''),
        ('cannot_save_time_index_to_segment', 4008, 'Cannot save time index to segment', null, null, ''),
        ('invalid_messages_count', 4009, 'Invalid messages count', null, null, ''),
        ('cannot_append_message', 4010, 'Cannot append message', null, null, ''),
        ('cannot_read_message', 4011, 'Cannot read message', null, null, ''),
        ('cannot_read_message_id', 4012, 'Cannot read message ID', null, null, ''),
        ('cannot_read_message_state', 4013, 'Cannot read message state', null, null, ''),
        ('cannot_read_message_timestamp', 4014, 'Cannot read message timestamp', null, null, ''),
        ('cannot_read_headers_length', 4015, 'Cannot read headers length', null, null, ''),
        ('cannot_read_headers_payload', 4016, 'Cannot read headers payload', null, null, ''),
        ('too_big_headers_payload', 4017, 'Too big headers payload', null, null, ''),
        ('invalid_header_key', 4018, 'Invalid header key', null, null, ''),
        ('invalid_header_value', 4019, 'Invalid header value', null, null, ''),
        ('cannot_read_message_length', 4020, 'Cannot read message length', null, null, ''),
        ('cannot_read_message_payload', 4021, 'Cannot save messages to segment', null, null, ''),
        ('too_big_message_payload', 4022, 'Too big message payload', null, null, ''),
        ('too_many_messages', 4023, 'Too many messages', null, null, ''),
        ('empty_message_payload', 4024, 'Empty message payload', null, null, ''),
        ('invalid_message_payload_length', 4025, 'Invalid message payload length', null, null, ''),
        ('cannot_read_message_checksum', 4026, 'Cannot read message checksum', null, null, ''),
        ('invalid_message_checksum', 4027, 'Invalid message checksum: {0}, expected: {1}, for offset: {2}', 'u32, u32, u64', null, ''),
        ('invalid_key_value_length', 4028, 'Invalid key value length', null, null, ''),
        ('invalid_offset', 4100, 'Invalid offset: {0}', 'u64', null, ''),
        ('cannot_read_consumer_offsets', 4101, 'Failed to read consumers offsets  for partition with ID: {0}', 'u32', null, ''),
        ('consumer_group_not_found', 5000, 'Consumer group with ID: {0} for topic with ID: {1} was not found.', 'u32, u32', null, ''),
        ('consumer_group_already_exists', 5001, 'Consumer group with ID: {0} for topic with ID: {1} already exists.', 'u32, u32', null, ''),
        ('consumer_group_member_not_found', 5002, 'Consumer group member with ID: {0} for group with ID: {1} for topic with ID: {2} was not found.', 'u32, u32, u32', null, ''),
        ('invalid_consumer_group_id', 5003, 'Invalid consumer group ID', null, null, ''),
        ('cannot_create_consumer_groups_directory', 5004, 'Failed to create directory for consumer groups for stream with ID: {0} and topic with ID: {1}', 'u32, u32', null, ''),
        ('cannot_read_consumer_groups', 5005, 'Failed to read consumer groups for topic with ID: {0} and stream with ID: {1}', 'u32, u32', null, ''),
        ('cannot_create_consumer_group_info', 5006, 'Failed to create consumer group info file for ID: {0} for topic with ID: {1} for stream with ID: {2}.', 'u32, u32, u32', null, ''),
        ('cannot_delete_consumer_group_info', 5007, 'Failed to delete consumer group info file for ID: {0} for topic with ID: {1} for stream with ID: {2}.', 'u32, u32, u32', null, '');

